const { gridSquareImageDimention } = require("../config/const");

const { createCanvas, loadImage } = require("canvas");
const canvas = createCanvas(gridSquareImageDimention, gridSquareImageDimention);
const context = canvas.getContext("2d");

// appending each image into canvas according to calculated coord
const drawOnDestination = async (image, destinationX, destinationY) => {
  const loadedImage = await loadImage(image.imageURL);
  let sourceImageDimention;
  let rest;
  let sourceX;
  let sourceY;
  if (loadedImage.width > loadedImage.height) {
    sourceImageDimention = loadedImage.height;
    rest = loadedImage.width - sourceImageDimention;
    sourceX = rest / 2;
    sourceY = 0;
  } else {
    sourceImageDimention = loadedImage.width;
    rest = loadedImage.height - sourceImageDimention;
    sourceX = 0;
    sourceY = rest / 2;
  }
  context.drawImage(
    loadedImage,
    sourceX,
    sourceY,
    sourceImageDimention,
    sourceImageDimention,
    destinationX,
    destinationY,
    gridSquareImageDimention / 3,
    gridSquareImageDimention / 3
  );
};

// default exposrt in the main logical function on how and which place the image portion going to be drowen
module.exports = async (res, images = []) => {
  // sorting the selection array by selected order
  images.sort((left, right) => left.position - right.position);
  // coordinates of image gooing to be placed in the canvas
  let destinationX = 0;
  let destinationY = 0;
  // iterating through all nine dealers
  for (let i = 0; i < images.length; i++) {
    // each image ging to be drawn in the canvas according to the coordinates generated by here
    const image = images[i];
    destinationX = parseInt(i % 3) * parseInt(gridSquareImageDimention / 3);
    destinationY = parseInt(i / 3) * parseInt(gridSquareImageDimention / 3);
    await drawOnDestination(image, destinationX, destinationY);
  }
  const data = canvas.toDataURL();
  return res.json({
    gridImage: data,
    items: images,
  });
};
